version: '3.8'
services:
    server:
        build: .
        container_name: server
        depends_on:
            - postgresql
        env_file: ./docker.env
        ports:
            - "8080:8080"
        volumes:
            - ./server/:/server
            - ./.sequelizerc:/.sequelizerc
        command: bash -c "sleep 2 && sequelize db:migrate && npm run start_server"
    
    postgresql:
        env_file: ./docker.env
        image: postgres:alpine3.15
        container_name: postgresql
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: always

    client_web:
        build: .
        container_name: web
        depends_on:
            - postgresql
            - server
        env_file: ./docker.env
        ports:
            - "8081:8081"
        volumes:
            - ./client_web/:/client_web
            - clishared:/clishared
        command: npm run start_web

    client_mobile:
        build: ./client_mobile
        container_name: client_mobile
        depends_on:
            - client_web
        volumes:
            - ./client_mobile/:/client_mobile
            - clishared:/clishared
        # entrypoint: ["sh", "mobile-entrypoint.sh"]
    
volumes:
    pgdata:
    clishared: